/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.stream.Stream;

import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() throws IOException {

        Path root = Paths.get("").toAbsolutePath();
        String rootPath = root.toString();
        try (Stream<Path> paths = Files.walk(Paths.get(rootPath))) {
            paths
                    .forEach(path -> {

                        System.out.println("Checking: " + path);
                    });
        }
    }
}
