/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Rule;
import org.junit.Test;
import org.junit.rules.TemporaryFolder;
import org.linter.projectstructure.ProjectStructure;
import org.linter.projectstructure.ProjectStructureFactory;

import java.io.IOException;
import java.nio.file.Path;
import java.util.List;

import static org.junit.Assert.*;

public class ProjectStructureFactoryTest {

    @Rule
    public TemporaryFolder tempFolder = new TemporaryFolder();

    @Test
    public void testMakeProjectStructureFromPath_RecursiveStructure() throws IOException {

        tempFolder.newFile("config.txt");
        tempFolder.newFolder("src");
        Path srcPath = tempFolder.getRoot().toPath().resolve("src");
        java.nio.file.Files.createFile(srcPath.resolve("Main.java"));

        ProjectStructureFactory factory = new ProjectStructureFactory();
        ProjectStructure rootInput = new ProjectStructure(tempFolder.getRoot().toPath());


        ProjectStructure result = factory.makeProjectStructureFromPath(rootInput);

        assertNotNull("Result should not be null", result);


        List<ProjectStructure> subDirectories = result.getChildren();
        assertEquals("Should have 1 child directory (src)", 1, subDirectories.size());
        assertEquals("src", subDirectories.get(0).getPath().getFileName().toString());


    }

    @Test
    public void testEmptyDirectory() throws IOException {
        ProjectStructureFactory factory = new ProjectStructureFactory();
        ProjectStructure emptyRoot = new ProjectStructure(tempFolder.getRoot().toPath());

        ProjectStructure result = factory.makeProjectStructureFromPath(emptyRoot);

        assertTrue("Children list should be empty", result.getChildren().isEmpty());
    }
}